const PREDICT_PAIR = {
  0: {
    name: 'Bitcoin',
    symbol: 'BTCUSDT',
    logo: {
      src: '/_next/static/media/btc-coin.694863e9.svg',
      height: 43,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'crypto',
  },
  1: {
    name: 'Ethereum',
    symbol: 'ETHUSDT',
    type: 'crypto',
  },
  3: {
    name: 'Doge',
    symbol: 'DOGEUSDT',
    logo: {
      src: '/_next/static/media/doge-coin.7ac30bf2.png',
      height: 169,
      width: 168,
      blurDataURL:
        'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAMAAADz0U65AAAAYFBMVEX18eK2nkqijUCMdRu2nDPIsmKwlSirkSpMaXGXgjDu6Nq+pE/9+vCulzKrki7Cq1zm4dPY0LrVu1+1o1fo157VwGvgz5KgnI/379K4sp7l3sbItnniyHvVwnymikDIrD+Aypx3AAAAEnRSTlP9tDE08fntsAAr/PH+rOrz/vohntheAAAACXBIWXMAAAsTAAALEwEAmpwYAAAARUlEQVR4nAXBBwKAIAwEsENGW5bKcuv/f2kCFsouCUNMsfbNAirwy/olmHqcV+wOpm77iI8DdQC+ELRto91Bgyc1BzXxD3HPAw8OD+3rAAAAAElFTkSuQmCC',
      blurWidth: 8,
      blurHeight: 8,
    },
    type: 'crypto',
  },
  10: {
    name: 'Solana',
    symbol: 'SOLUSDT',
    logo: {
      src: '/_next/static/media/solana-coin.bb9739a2.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'crypto',
  },
  11: {
    name: 'MakerDAO',
    symbol: 'MKRUSDT',
    logo: {
      src: '/_next/static/media/makerdao-coin.b30de98f.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'crypto',
  },
  80: {
    name: 'Arbitrum',
    symbol: 'ARBUSDT',
    logo: {
      src: '/_next/static/media/arbitrum-coin.0133d7cc.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'crypto',
  },
  121: {
    name: 'Injective',
    symbol: 'INJUSDT',
    logo: {
      src: '/_next/static/media/injective-coin.7642c4db.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'crypto',
  },
  205: {
    name: 'Celestia',
    symbol: 'TIAUSDT',
    logo: {
      src: '/_next/static/media/celestia-coin.fb88c084.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'crypto',
  },
  208: {
    name: 'Sei',
    symbol: 'SEIUSDT',
    logo: {
      src: '/_next/static/media/sei-coin.8ba3ea2a.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'crypto',
  },
  301: {
    name: 'Ondo',
    symbol: 'ONDOUSDT',
    logo: {
      src: '/_next/static/media/ondo-coin.50e50731.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'crypto',
  },
  5e3: {
    name: 'EUR/USD',
    symbol: 'EURUSD',
    type: 'forex',
  },
  5001: {
    name: 'USD/JPY',
    symbol: 'USDJPY',
    logo: {
      src: '/_next/static/media/USD_JPY.e43368d4.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'forex',
  },
  5002: {
    name: 'GBP/USD',
    symbol: 'GBPUSD',
    logo: {
      src: '/_next/static/media/GBP_USD.0f3c8816.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'forex',
  },
  5003: {
    name: 'EUR/GBP',
    symbol: 'EURGBP',
    type: 'forex',
  },
  5004: {
    name: 'USD/KRW',
    symbol: 'USDKRW',
    logo: {
      src: '/_next/static/media/USD_KRW.37f45363.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'forex',
  },
  5005: {
    name: 'USD/HKD',
    symbol: 'USDHKD',
    logo: {
      src: '/_next/static/media/USD_HKD.5bc91926.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'forex',
  },
  5006: {
    name: 'USD/INR',
    symbol: 'USDINR',
    logo: {
      src: '/_next/static/media/USD_INR.9ac526f8.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'forex',
  },
  5007: {
    name: 'USD/CNY',
    symbol: 'USDCNY',
    logo: {
      src: '/_next/static/media/USD_CNY.84b6f78c.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'forex',
  },
  5008: {
    name: 'USD/SGD',
    symbol: 'USDSGD',
    logo: {
      src: '/_next/static/media/USD_SGD.ab30336f.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'forex',
  },
  5011: {
    name: 'USD/CAD',
    symbol: 'USDCAD',
    logo: {
      src: '/_next/static/media/USD_CAD.f0254f5c.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'forex',
  },
  5014: {
    name: 'USD/VND',
    symbol: 'USDVND',
    logo: {
      src: '/_next/static/media/USD_VND.e753e5d5.svg',
      height: 42,
      width: 42,
      blurWidth: 0,
      blurHeight: 0,
    },
    type: 'forex',
  },
};

const PREDICT_CONTRACT = {
  implementation: '0xFaB4C578741bE1E78983Ab0A201e45BcEe52ceA0',
  proxy: '0x032139f44650481f4d6000c078820B8E734bF253',
};

module.exports = { PREDICT_PAIR, PREDICT_CONTRACT };
